In [9]:
import tensorflow as tf

In [10]:
d = tf.constant([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]], dtype=tf.float16)

In [11]:
sess = tf.Session()

In [12]:
sess.run(d)

array([[[[  1.,   2.,   3.],
         [  4.,   5.,   6.]],

        [[  7.,   8.,   9.],
         [ 10.,  11.,  12.]]]], dtype=float16)

In [13]:
d.get_shape()

TensorShape([Dimension(1), Dimension(2), Dimension(2), Dimension(3)])

In [14]:
d1 = tf.reshape(d, [-1, 3])

In [15]:
sess.run(d1)

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]], dtype=float16)

In [16]:
d1.get_shape()

TensorShape([Dimension(4), Dimension(3)])

In [17]:
labels = tf.constant([[[1, 0], [1, 0]]])

In [18]:
labels.get_shape()

TensorShape([Dimension(1), Dimension(2), Dimension(2)])

In [19]:
th = tf.zeros(labels.get_shape(), dtype=tf.int32)

In [20]:
b = tf.greater(labels, th)

In [21]:
b.get_shape()

TensorShape([Dimension(1), Dimension(2), Dimension(2)])

In [22]:
sess.run(b)

array([[[ True, False],
        [ True, False]]], dtype=bool)

In [23]:
b1 = tf.reshape(b, [-1])

In [24]:
b1.get_shape()

TensorShape([Dimension(4)])

In [50]:
sess.run(d1)

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]], dtype=float16)

In [51]:
sess.run(b1)

array([ True, False,  True, False], dtype=bool)

In [52]:
ret = tf.boolean_mask(d1, b1)

In [53]:
sess.run(ret)

array([[ 1.,  2.,  3.],
       [ 7.,  8.,  9.]], dtype=float16)

In [5]:
import os
label_name_list = [ ]
image_name_list = [ ]

for (dirpath, dirnames, filenames) in os.walk('training_set/labels'):
    label_name_list.extend(map(lambda x: 'training_set/labels/' + x, filenames))
    image_name_list.extend(map(lambda x: 'training_set/images/' + x.replace('.dat', '.png'), filenames))
    break
print label_name_list
print image_name_list

['training_set/labels/1c1e9e56-47f7-4624-a995-93fea5a7660a.dat', 'training_set/labels/de604e7a-18c5-4c7a-a413-c7362b4ac082.dat', 'training_set/labels/a463e84a-105f-444d-83e3-4180c1410140.dat']
['training_set/images/1c1e9e56-47f7-4624-a995-93fea5a7660a.png', 'training_set/images/de604e7a-18c5-4c7a-a413-c7362b4ac082.png', 'training_set/images/a463e84a-105f-444d-83e3-4180c1410140.png']


In [12]:
import tensorflow as tf
import numpy as np
#from scipy import misc

d = np.array([[255, 0], [255, 0]])

#misc.imsave
print d

[[255   0]
 [255   0]]


In [8]:
b = tf.reshape(a, [-1, 1])
sess.run(b)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)